version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 30 --keep-alive 5
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - app_logs:/app/logs

  bot:
    build: .
    restart: always
    command: python tg_bot/bot.py
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    depends_on:
      - web
    volumes:
      - app_logs:/app/logs

volumes:
  postgres_data:
  app_logs:
