# Generated by Django 6.0.1 on 2026-01-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название кампании')),
                ('admin_telegram_id', models.BigIntegerField(verbose_name='Telegram ID админа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер раунда')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Активен'), ('ended', 'Завершён')], default='pending', max_length=20)),
                ('winners_count', models.PositiveSmallIntegerField(default=3, verbose_name='Сколько победителей выбрать')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='voting.campaign')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
                'unique_together': {('campaign', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, verbose_name='Описание (опционально)')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='voting.round')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.BigIntegerField(verbose_name='Telegram ID проголосовавшего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.round')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('round', 'user_telegram_id')},
            },
        ),
    ]
