# Generated by Django 6.0.1 on 2026-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность раунда в минутах'),
        ),
        migrations.AddField(
            model_name='round',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершится в'),
        ),
    ]
