# Generated by Django 6.0.1 on 2026-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущий раунд для голосования'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winners_count',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Сколько призовых мест'),
        ),
    ]
