# Generated by Django 6.0.1 on 2026-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_round_is_current_alter_round_winners_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('round', 'user_telegram_id', 'participant')},
        ),
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('individual', 'Индивидуальный')], default='standard', max_length=20, verbose_name='Тип раунда'),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, null=True, verbose_name='Выбор (для индивидуального)'),
        ),
    ]
