# Generated by Django 6.0.1 on 2026-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_round_duration_minutes_round_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ends_at',
        ),
        migrations.AlterField(
            model_name='round',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён в'),
        ),
    ]
