# Generated by Django 6.0.1 on 2026-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_round_duration_minutes_remove_round_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['order_number'], 'verbose_name': 'Кампания', 'verbose_name_plural': 'Кампании'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['order_number', 'full_name'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-started_at'], 'verbose_name': 'Раунд', 'verbose_name_plural': 'Раунды'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='order_number',
            field=models.PositiveIntegerField(default=9999, editable=False, unique=True, verbose_name='Порядковый номер кампании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='order_number',
            field=models.PositiveIntegerField(default=9999, editable=False, verbose_name='Порядковый номер участника в раунде'),
            preserve_default=False,
        ),
    ]
