# Generated by Django 6.0.1 on 2026-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_vote_unique_together_round_type_vote_choice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['campaign', 'status', 'is_current'], name='voting_roun_campaig_d14880_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['round', 'user_telegram_id'], name='voting_vote_round_i_02f83f_idx'),
        ),
    ]
