# Generated by Django 6.0.1 on 2026-03-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_round_voting_roun_campaig_d14880_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['order_number', 'full_name']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='round',
            name='voting_roun_campaig_d14880_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='order_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Активен'), ('ended', 'Завершён (Скрыт)'), ('published', 'Опубликован (Результаты открыты)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('individual', 'Индивидуальный')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='round',
            name='winners_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_telegram_id',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['status', 'is_current'], name='voting_roun_status_7cb508_idx'),
        ),
    ]
